version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis

  celery_worker:
    build: ./backend
    command: celery -A celery_app.celery worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis

  # flower:
    # container_name: flower
    # build: ./backend
    # command: celery -A celery_app.celery flower --port=5555
    # ports:
    #   - "5556:5555"
    # env_file:
    #   - ./backend/.env
    # environment:
    #   - PYTHONPATH=/app
    # depends_on:
    #   - backend
    #   - celery_worker

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
